@startuml

class Recursividad2Think {

+ productoPares(int) : int
+ contarCifras(int) : int
+ cuadrado(int) : int
+ eliminarLetra(String,char) : String
+ reemplazarLetra(String,char,char) : String
+ esPalindromo(String) : boolean
+ duplicarLista(List<Integer>) : List<Integer>
+ sumaPosicionesPares(List<Integer>) : int
+ decimalABinario(int) : String

}

@enduml